apiVersion: sns.awscontrolapi.crossplane.io/v1alpha1
kind: Topic
metadata:
  name: test-topic
spec:
  forProvider:
    region: us-west-2
    displayName: testtopic
    tags:
      usage: test
      owner: orchestration
      namespace: system
  providerConfigRef:
    name: default
